### ISSUE TITLE
Allow the dashboard app to choose current speaker

### ISSUE THREAD

**Issue by francissmedley** [NHS-App/Speak-Up#27]
add a section of the dashboard app that gets all the speakers from the database for the current event (that have been added through the content management system, and puts them in a dropdown list and then allow the dashboard user to select the speaker that is currently speaking, the questions for only this speaker are then what will be shown on the projection view

**Comment by Machinewarlock** [comment]
https://github.com/NHS-App/Speak-Up/pull/58
https://github.com/NHS-App/Speak-Up/pull/61

Done Here.
