### ISSUE TITLE
allow content management system to group things into events

### ISSUE THREAD

**Issue by francissmedley** [NHS-App/Speak-Up#28]
e.g create a new event and then inside that event you can add new initiatives etc, all references to the database from the app/projection view will then need to know the current event (by reading a separate field from the database) so they can put this at the beginning of the path. The dashboard user should then also have the option to choose the current event from a dropdown list of all the events (this will change the current event field in the database to inform app and projection view

**Comment by Machinewarlock** [comment]
Dashboard side done here 
https://github.com/NHS-App/Speak-Up/pull/63
https://github.com/NHS-App/Speak-Up/pull/66 

App and projection side still need to be done before this issue can be closed.

**Comment by Machinewarlock** [comment]
App side done here and also further updated dashboard:

https://github.com/NHS-App/Speak-Up/pull/83

Projection done here:

https://github.com/NHS-App/Speak-Up/pull/84
